"""Initial schema

Revision ID: 065dad471fe0
Revises: 
Create Date: 2026-05-31 10:07:48.903388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065dad471fe0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('active_students', sa.Integer(), nullable=True),
    sa.Column('total_teachers', sa.Integer(), nullable=True),
    sa.Column('critical_risk_count', sa.Integer(), nullable=True),
    sa.Column('high_risk_count', sa.Integer(), nullable=True),
    sa.Column('moderate_risk_count', sa.Integer(), nullable=True),
    sa.Column('low_risk_count', sa.Integer(), nullable=True),
    sa.Column('avg_risk_score', sa.Float(), nullable=True),
    sa.Column('avg_attendance_rate', sa.Float(), nullable=True),
    sa.Column('absent_today', sa.Integer(), nullable=True),
    sa.Column('avg_marks_percentage', sa.Float(), nullable=True),
    sa.Column('subjects_failing', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_score', sa.Float(), nullable=True),
    sa.Column('low_engagement_count', sa.Integer(), nullable=True),
    sa.Column('total_interventions', sa.Integer(), nullable=True),
    sa.Column('pending_interventions', sa.Integer(), nullable=True),
    sa.Column('completed_interventions', sa.Integer(), nullable=True),
    sa.Column('intervention_success_rate', sa.Float(), nullable=True),
    sa.Column('school_health_score', sa.Float(), nullable=True),
    sa.Column('health_grade', sa.String(length=2), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_snapshot_date'), 'analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_table('import_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_health_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('at_risk_students', sa.Integer(), nullable=True),
    sa.Column('critical_cases', sa.Integer(), nullable=True),
    sa.Column('avg_attendance_rate', sa.Float(), nullable=True),
    sa.Column('avg_performance', sa.Float(), nullable=True),
    sa.Column('avg_engagement_score', sa.Float(), nullable=True),
    sa.Column('intervention_success_rate', sa.Float(), nullable=True),
    sa.Column('teacher_burnout_rate', sa.Float(), nullable=True),
    sa.Column('overall_health_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('class', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('roll_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('subjects', sa.Text(), nullable=True),
    sa.Column('classes_assigned', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('marked_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=True),
    sa.Column('pattern_strength', sa.Float(), nullable=True),
    sa.Column('detection_date', sa.Date(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('participation_score', sa.Float(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=True),
    sa.Column('class_interaction_level', sa.String(length=20), nullable=True),
    sa.Column('focus_level', sa.String(length=20), nullable=True),
    sa.Column('mood_observed', sa.String(length=30), nullable=True),
    sa.Column('observer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('assignment_name', sa.String(length=200), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('teacher_remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('assessment_type', sa.String(length=50), nullable=True),
    sa.Column('assessment_name', sa.String(length=200), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('obtained_marks', sa.Float(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('teacher_remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('prediction_horizon_days', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('observation_type', sa.String(length=50), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('transcribed_text', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('concern_level', sa.String(length=20), nullable=True),
    sa.Column('extracted_insights', sa.JSON(), nullable=True),
    sa.Column('processing_confidence', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_workload',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('classes_taught', sa.Integer(), nullable=True),
    sa.Column('assignments_corrected', sa.Integer(), nullable=True),
    sa.Column('students_mentored', sa.Integer(), nullable=True),
    sa.Column('interventions_handled', sa.Integer(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.String(length=20), nullable=True),
    sa.Column('burnout_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'date', name='_teacher_date_uc')
    )
    op.create_table('interventions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('risk_prediction_id', sa.String(length=36), nullable=True),
    sa.Column('intervention_type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('recommended_by', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('ai_recommendation_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['risk_prediction_id'], ['risk_predictions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    op.drop_table('teacher_workload')
    op.drop_table('teacher_observations')
    op.drop_table('risk_predictions')
    op.drop_table('performance')
    op.drop_table('homework_submissions')
    op.drop_table('engagement_logs')
    op.drop_table('behavioral_patterns')
    op.drop_table('attendance')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('school_health_metrics')
    op.drop_table('import_history')
    op.drop_index(op.f('ix_analytics_snapshots_snapshot_date'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
